#!/usr/bin/env node

'use strict'

var isNumber = require('is-number')
var path = require('path')
var meow = require('meow')

var stdin = process.stdin

var write = function (value) {
  if (value !== undefined) {
    console.log(value)
  }
  return value
}

var run = function (job, args) {
  var result = job.apply(null, args)

  if (result && typeof result.then === 'function') {
    result.then(write)
  } else {
    write(result)
  }
}

var cli = meow([
  'Usage',
  '  $ effectuate script.js [arguments]',
  '',
  'Examples',
  '  $ effectuate add.js 5 12',
  '  17',
  '',
  '  $ echo 5 | effectuate add.js 9',
  '  14'
])

var script = cli.input[0]

if (!script) {
  cli.showHelp()
}

var task = require(path.resolve(process.cwd(), script))
var input = cli.input.slice(1).concat(
  Object.keys(cli.flags).length ? cli.flags : []
)

if (stdin.isTTY) {
  run(task, input)
} else {
  stdin.setEncoding('utf8')
  stdin.on('readable', function () {
    var chunk = stdin.read()

    if (chunk != null) {
      run(task, [isNumber(chunk) ? +chunk : chunk].concat(input))
    }
  })
}
