#!/usr/bin/env node

'use strict'

const isNumber = require('is-number')
const path = require('path')
const meow = require('meow')

const stdin = process.stdin

const write = value => {
  if (value !== undefined) {
    console.log(value)
  }
  return value
}

const run = (job, args) => {
  return Promise.resolve(job.apply(null, args)).then(write)
}

const cli = meow(`
  Usage
    $ effectuate script.js [arguments]

  Examples
    $ effectuate add.js 5 12
    17

    $ echo 5 | effectuate add.js 9
    14
`)

const script = cli.input[0]

if (!script) {
  cli.showHelp()
}

const task = require(path.resolve(process.cwd(), script))
const input = cli.input.slice(1).concat(
  Object.keys(cli.flags).length ? cli.flags : []
)

if (stdin.isTTY) {
  run(task, input)
} else {
  stdin.setEncoding('utf8')
  stdin.on('readable', () => {
    const chunk = stdin.read()

    if (chunk != null) {
      run(task, [isNumber(chunk) ? +chunk : chunk].concat(input))
    }
  })
}
